### ISSUE TITLE
전체 todo

### ISSUE THREAD

**Issue by ka02song** [rockets-yj/rockets#10]
- [ ] cloudFormation 가져오는 법 찾기
- [ ] Helm 사용법
----------------------------------------------------
- [ ] web 만들기 (로그인, 회원가입, 생성상태 보기) -> git 사용하기 / db연결확인
- [ ] 메인페이지 (로그인, 회원가입)
- [ ] 로그인 성공 -> 서비스 등록 버튼
- [ ] 서비스 등록 페이지
- [ ] admin페이지
