### ISSUE TITLE
2023-11-21 todo

### ISSUE THREAD

**Issue by ka02song** [rockets-yj/rockets#6]
- [ ] 세부 계획 정하기
- [ ] DB 구조 설계
- [x] 인스턴스 생성
- [x] 회원정보 RDS 생성
- [ ] 쿠버네티스 대시보드 설치
- [x] 작은 demo(html파일 혹은 django 같은 웹 프레임워크) 로 eks 혹은 자신의 vmware 등에서 실행해보고 확인해보기
- [ ] vpc 나 subnet 같은 네트워크적인 문제들은 기본값(default) 으로 설정
- [ ] 3tier 샘플 찾기
