### ISSUE TITLE
2023-11-22 todo

### ISSUE THREAD

**Issue by ka02song** [rockets-yj/rockets#7]
- [x] 데모 이어 만들기
- [x] nginx 등 이미지 올려서 해보기
- [ ] 다른 서비스도 둘러보기
- [ ] yaml 파일 옵션 알아보기
